### ISSUE TITLE
Add a base namespace configuration option

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-mailable-test#12]
Add a `base_namespace` configuration key (default: `App\Mails`), this would allow

```
php artisan mail:send-test MyMailable
```

instead of

```
php artisan mail:send-test "App\Mails\MyMailable"
```

First the package should check if the mailable class exists as is `MyMailable`, then prepend the base namespace if nothing was found and try again.

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that adds this to the package.

**Comment by fetzi** [comment]
@freekmurze I will send a PR for this one.
